// prisma/seed-data.ts

export const seedUsers = [
  {
    id: 1n,
    email: "demo1@sucvatlaixe.com",
    passwordHash: "hash-demo-1",
    displayName: "Demo 1",
    rank: "Bạc",
  },
  {
    id: 2n,
    email: "demo2@sucvatlaixe.com",
    passwordHash: "hash-demo-2",
    displayName: "Demo 2",
    rank: "Vàng",
  },
  {
    id: 3n,
    email: "demo3@sucvatlaixe.com",
    passwordHash: "hash-demo-3",
    displayName: "Demo 3",
    rank: "Kim Cương",
  },
];

export const seedReports = [
  {
    id: 1n,
    authorId: 1n,
    plateNumber: "51A-12345",
    title: "Đánh võng trên cầu",
    description: "Thằng này chạy như điên, đánh võng trên cầu vượt, suýt tông mấy xe phía trước.",
    carType: "Xe máy",
    location: "TP.HCM - Cầu Sài Gòn",
    categoryTag: "Mới Cập Nhật",
  },
  {
    id: 2n,
    authorId: 1n,
    plateNumber: "30G-56789",
    title: "Đỗ xe chắn cửa nhà",
    description: "Đỗ chắn hết cửa nhà người ta, gọi hoài không ra dắt, chủ nhà phải chờ gần 1 tiếng.",
    carType: "Ô tô",
    location: "Hà Nội - Cầu Giấy",
    categoryTag: "Nhiều Report",
  },
  {
    id: 3n,
    authorId: 2n,
    plateNumber: "59X1-88888",
    title: "Lấn làn, bóp còi inh ỏi",
    description: "Kẹt xe nhưng vẫn cố lấn làn, bóp còi liên tục gây ồn ào khó chịu.",
    carType: "Xe máy",
    location: "TP.HCM - Quận 1",
    categoryTag: "Mới Cập Nhật",
  },
  {
    id: 4n,
    authorId: 2n,
    plateNumber: "43A-01234",
    title: "Đua xe lúc nửa đêm",
    description: "Nhóm 4-5 xe nẹt pô, chạy tốc độ cao trong khu dân cư lúc hơn 1h sáng.",
    carType: "Ô tô",
    location: "Đà Nẵng - Hải Châu",
    categoryTag: "Nhiều Report",
  },
  {
    id: 5n,
    authorId: 3n,
    plateNumber: "50N1-43210",
    title: "Không nhường đường cho xe cấp cứu",
    description: "Xe cấp cứu xin đường rõ ràng nhưng vẫn cố chen, không chịu né.",
    carType: "Xe máy",
    location: "TP.HCM - Quốc lộ 13",
    categoryTag: "Nhiều Report",
  },
  {
    id: 6n,
    authorId: 3n,
    plateNumber: "29B-99999",
    title: "Quay đầu xe giữa hầm",
    description: "Tự nhiên dừng giữa hầm rồi quay đầu xe, cực kỳ nguy hiểm.",
    carType: "Ô tô",
    location: "Hà Nội - Hầm Kim Liên",
    categoryTag: "Mới Cập Nhật",
  },
  {
    id: 7n,
    authorId: 1n,
    plateNumber: "60C-123.45",
    title: "Xe tải chạy ẩu",
    description: "Xe tải chạy sát đuôi, thỉnh thoảng đánh lái bất ngờ.",
    carType: "Xe tải",
    location: "Đồng Nai",
    categoryTag: "Nhiều Report",
  },
  {
    id: 8n,
    authorId: 2n,
    plateNumber: "51F-54321",
    title: "Đỗ xe trên vạch người đi bộ",
    description: "Đèn đỏ mà vẫn tràn hết lên vạch dành cho người đi bộ.",
    carType: "Ô tô",
    location: "TP.HCM - Quận 3",
    categoryTag: "Mới Cập Nhật",
  },
  {
    id: 9n,
    authorId: 2n,
    plateNumber: "47H1-11111",
    title: "Chở hàng cồng kềnh",
    description: "Chở đồ phía sau dài cả mét, không có dây chằng, dễ rơi xuống đường.",
    carType: "Xe máy",
    location: "Đắk Lắk",
    categoryTag: "Mới Cập Nhật",
  },
  {
    id: 10n,
    authorId: 3n,
    plateNumber: "30E-22222",
    title: "Vượt đèn vàng như đèn xanh",
    description: "Đèn vàng là tăng ga vượt luôn, suýt tông xe phía bên kia.",
    carType: "Ô tô",
    location: "Hà Nội - Hoàn Kiếm",
    categoryTag: "Nhiều Report",
  },
  {
    id: 11n,
    authorId: 1n,
    plateNumber: "51H-33333",
    title: "Đi ngược chiều trong hẻm nhỏ",
    description: "Hẻm chỉ đủ một xe mà vẫn cố chạy ngược chiều, bắt người khác lùi.",
    carType: "Xe máy",
    location: "TP.HCM - Bình Thạnh",
    categoryTag: "Mới Cập Nhật",
  },
  {
    id: 12n,
    authorId: 3n,
    plateNumber: "72A-44444",
    title: "Vừa lái xe vừa bấm điện thoại",
    description: "Chạy chậm giữa đường, mắt nhìn điện thoại suốt, rất nguy hiểm.",
    carType: "Ô tô",
    location: "Vũng Tàu",
    categoryTag: "Mới Cập Nhật",
  },
];

export const seedComments = [
  {
    id: 1n,
    reportId: 1n,
    authorId: 2n,
    content: "Thằng này quá nguy hiểm, nên report biển số cho công an giao thông.",
    likeCount: 2,
  },
  {
    id: 2n,
    reportId: 1n,
    authorId: 3n,
    content: "Tôi cũng gặp nó đoạn này rồi, chạy như điên.",
    likeCount: 1,
  },
  {
    id: 3n,
    reportId: 2n,
    authorId: 1n,
    content: "Đỗ kiểu này mà nhà có việc gấp thì sao ra được trời.",
    likeCount: 0,
  },
  {
    id: 4n,
    reportId: 3n,
    authorId: 1n,
    content: "Mỗi ngày đi làm đều gặp mấy đối tượng như thế này.",
    likeCount: 0,
  },
  {
    id: 5n,
    reportId: 5n,
    authorId: 2n,
    content: "Không nhường xe cấp cứu thì chịu rồi.",
    likeCount: 3,
  },
];

export const seedCommentMedia = [
  {
    id: 1n,
    commentId: 1n,
    mediaType: "image",
    url: "https://example.com/comments/1/image1.jpg",
    fileName: "51A-12345-cau-saigon.jpg",
  },
  {
    id: 2n,
    commentId: 2n,
    mediaType: "video",
    url: "https://example.com/comments/2/video1.mp4",
    fileName: "51A-12345-clip.mp4",
    durationSec: 15,
  },
  {
    id: 3n,
    commentId: 3n,
    mediaType: "image",
    url: "https://example.com/comments/3/image1.jpg",
    fileName: "30G-56789-doxe.jpg",
  },
];

export const seedReportMedia = [
  {
    id: 1n,
    reportId: 1n,
    mediaType: "image",
    url: "https://example.com/reports/1/img-main.jpg",
    fileName: "report-1-main.jpg",
  },
  {
    id: 2n,
    reportId: 2n,
    mediaType: "image",
    url: "https://example.com/reports/2/img-main.jpg",
    fileName: "report-2-main.jpg",
  },
  {
    id: 3n,
    reportId: 4n,
    mediaType: "video",
    url: "https://example.com/reports/4/duaxe.mp4",
    fileName: "duaxe.mp4",
    durationSec: 20,
  },
];

export const seedUserLikes  = [
  // like report
  {
    userId: 1n,
    targetType: "report",
    targetId: 1n,
  },
  {
    userId: 2n,
    targetType: "report",
    targetId: 1n,
  },
  {
    userId: 3n,
    targetType: "report",
    targetId: 2n,
  },
  {
    userId: 2n,
    targetType: "report",
    targetId: 5n,
  },
  // like comment
  {
    userId: 1n,
    targetType: "comment",
    targetId: 1n,
  },
  {
    userId: 3n,
    targetType: "comment",
    targetId: 1n,
  },
  {
    userId: 3n,
    targetType: "comment",
    targetId: 5n,
  },
];
